scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
 #   scheme: https
    static_configs:
      - targets: ['192.168.56.1:8080']  
  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['192.168.56.1:9182']